# Permalinks
#

permalink:           pretty


# Setup
title:               Si[n]ombre
tagline:             ''
description:         'Si[n]ombre es un proyecto colaborativo por Delgado Photography y South First Media'
url:                 yuquiyu2017.github.io
baseurl:             'https://yuquiyu2017.github.io'
paginate:            5

# About/contact
author:
  name:              DP y SFM
  url:               #
  email:             #

# Custom vars
version:             1.0.0
