# Permalinks
#

permalink:           pretty


# Setup
title:               Here & There
tagline:             ''
description:         'Here & There is a collaborative art project.'
url:                 yuquiyu2017.github.io
baseurl:             'https://yuquiyu2017.github.io'
paginate:            5

# About/contact
author:
  name:              Here & There
  url:               #
  email:             #

# Custom vars
version:             1.0.0
