# Permalinks
#

permalink:           pretty


# Setup
title:               Mandalas
tagline:             'Mensajes Positivos Para La Humanidad'
description:         'Un proyecto de Delgado Photography y South First Media'
url:                 https://yuquiyu2017.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              DP y SFM
  url:               #
  email:             #

# Custom vars
version:             1.0.0
